### ISSUE TITLE
Contributions list

### ISSUE THREAD

**Issue by kukimik** [TristanCacqueray/TristanCacqueray.github.io#4]
Hello! Is the contributions list https://tristancacqueray.github.io/contributions generated automatically? If so, could you perhaps share the script you are using?

**Comment by TristanCacqueray** [comment]
Hey, there are instructions at the bottom of the source, see: https://raw.githubusercontent.com/TristanCacqueray/TristanCacqueray.github.io/main/content/contributions.md .

Though it would be nice if this was updated automatically. We might be able to do that with [monocle](https://changemetrics.io), the initial work has been implemented in https://github.com/change-metrics/monocle/pull/1061 , but a query to list the contributions still needs to be implemented.

**Comment by kukimik** [comment]
Ah, thanks a lot!
